"""Markdown report generator for PentBoard engagements."""

from datetime import datetime
from pentboard.models.database import Database, Engagement, Finding, Target, Severity


SEVERITY_EMOJI = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}


def generate_report(db: Database, engagement_id: int) -> str:
    """Generate a full penetration test report in Markdown."""
    engagement = db.get_engagement(engagement_id)
    if not engagement:
        return "# Error: Engagement not found"

    targets = db.get_targets(engagement_id)
    findings = db.get_findings(engagement_id)
    stats = db.get_engagement_stats(engagement_id)

    target_map = {t.id: t for t in targets}

    lines = []

    # Header
    lines.append(f"# Penetration Test Report: {engagement.name}")
    lines.append("")
    lines.append(f"**Client:** {engagement.client or 'N/A'}")
    lines.append(f"**Date:** {engagement.start_date or 'N/A'} to {engagement.end_date or 'N/A'}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append(f"**Generated by:** PentBoard")
    lines.append("")

    # Executive Summary
    lines.append("---")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append("")
    lines.append(
        f"This penetration test assessed **{stats['targets']}** target(s) "
        f"and identified **{stats['total_findings']}** finding(s). "
        f"Of the targets assessed, **{stats['compromised']}** were compromised."
    )
    lines.append("")

    # Severity breakdown
    lines.append("### Findings by Severity")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    for sev in Severity:
        count = stats["findings_by_severity"].get(sev.value, 0)
        emoji = SEVERITY_EMOJI.get(sev.value, "")
        lines.append(f"| {emoji} {sev.value.capitalize()} | {count} |")
    lines.append("")

    # Scope
    if engagement.scope:
        lines.append("## Scope")
        lines.append("")
        lines.append(engagement.scope)
        lines.append("")

    # Targets
    lines.append("## Targets")
    lines.append("")
    if targets:
        lines.append("| Host | IP | OS | Status | Open Ports |")
        lines.append("|------|----|----|--------|------------|")
        for t in targets:
            port_list = t.port_list
            port_str = ", ".join(str(p) for p in port_list[:10])
            if len(port_list) > 10:
                port_str += f" (+{len(port_list) - 10} more)"
            status_display = t.status.replace("_", " ").title()
            lines.append(
                f"| {t.hostname or t.host} | {t.ip} | {t.os_guess or 'Unknown'} | {status_display} | {port_str or 'N/A'} |"
            )
        lines.append("")
    else:
        lines.append("No targets recorded.")
        lines.append("")

    # Detailed Findings
    lines.append("## Detailed Findings")
    lines.append("")

    if not findings:
        lines.append("No findings recorded.")
        lines.append("")
    else:
        for i, f in enumerate(findings, 1):
            emoji = SEVERITY_EMOJI.get(f.severity, "")
            lines.append(f"### {i}. {emoji} {f.title}")
            lines.append("")
            lines.append(f"**Severity:** {f.severity.capitalize()}")
            lines.append(f"**Status:** {f.status.replace('_', ' ').title()}")

            if f.target_id and f.target_id in target_map:
                target = target_map[f.target_id]
                lines.append(f"**Target:** {target.display_name}")

            if f.port:
                lines.append(f"**Port:** {f.port}")
            if f.service:
                lines.append(f"**Service:** {f.service}")
            if f.cwe:
                lines.append(f"**CWE:** {f.cwe}")
            if f.cvss:
                lines.append(f"**CVSS:** {f.cvss}")
            if f.tool_source:
                lines.append(f"**Tool:** {f.tool_source}")

            lines.append("")

            if f.description:
                lines.append("**Description:**")
                lines.append("")
                lines.append(f"{f.description}")
                lines.append("")

            if f.evidence:
                lines.append("**Evidence:**")
                lines.append("")
                lines.append(f"```")
                lines.append(f"{f.evidence}")
                lines.append(f"```")
                lines.append("")

            if f.remediation:
                lines.append("**Remediation:**")
                lines.append("")
                lines.append(f"{f.remediation}")
                lines.append("")

            lines.append("---")
            lines.append("")

    # Notes
    if engagement.notes:
        lines.append("## Notes")
        lines.append("")
        lines.append(engagement.notes)
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by [PentBoard](https://github.com/AliRai7/pentboard) -- Terminal Pentest Mission Control*")

    return "\n".join(lines)
